### ISSUE TITLE
iTerm 2 3.3.9 Command is not sent

### ISSUE THREAD

**Issue by btutal** [vitorgalvao/custom-alfred-iterm-scripts#42]
Hi,

I am using the latest version of script

````
on alfred_script(q)
	tell application "iTerm"
		if application "iTerm" is running then
			try
				tell the first window to create tab with default profile
			on error
				create window with default profile
			end try
		end if

		delay 0.1 -- If we do not wait, the command may fail to send

		tell the first window to tell current session to write text q
		activate
	end tell
end alfred_script
````
but I've realised when the iTerm is not running, command is not sent. It helps even if there is no window and application is running but if you quit with cmd+q and try, script doesn't send command, just opens iTerm window.

**Comment by vitorgalvao** [comment]
Increase the delay to `1` or `2`. Does that work?

What’s your macOS version?

**Comment by btutal** [comment]
> Increase the delay to `1` or `2`. Does that work?
It didn't help at all and I don't think it is related with this, since with the script in #41 iTerm2 starts faster than this and still works. 

> What’s your macOS version?
10.15.4

**Comment by vitorgalvao** [comment]
> since with the script in #41 iTerm2 starts faster than this and still works.

You seem to be the only one experiencing an issue with this version so far, so if you have another version that works, use that.

The current one is only a stopgap until Alfred can support JXA for the scripting, anyway.
