### ISSUE TITLE
Fails to send command if iTerm2 3.3.9 isn't already running

### ISSUE THREAD

**Issue by sharjeelsayed** [vitorgalvao/custom-alfred-iterm-scripts#43]
Fails to send command if iTerm2 3.3.9 isn't already running
Works if iTerm2 app is already open

**Comment by vitorgalvao** [comment]
Are you using [the latest version](https://github.com/vitorgalvao/custom-alfred-iterm-scripts/blob/master/custom_iterm_script.applescript)?

Try increasing [the delay](https://github.com/vitorgalvao/custom-alfred-iterm-scripts/blob/8683f5ebaac267bd98e080004bf841f53c5e2c1a/custom_iterm_script.applescript#L11). Make it something high at first (like `1`).

**Comment by alihazemfarouk** [comment]
I am facing the exact same issue, increasing the delay does not solve it.

**Comment by vitorgalvao** [comment]
What’s the macOS version?

**Comment by alihazemfarouk** [comment]
> What’s the macOS version?

10.15.4
I am also using zsh and oh my zsh, don't know if this makes any difference

**Comment by alihazemfarouk** [comment]
The script from #41 seems to work.

**Comment by vitorgalvao** [comment]
I’m on the 3.3.10 beta, so it’s not an iTerm2 version thing. But I am on Mojave, not Catalina.

I’m wary of doing changes now, because it’s possible Alfred will support JXA for the Terminal feature soon, at which point I’ll replace the script. But if it’s not there by the next point release, I’ll take a look.

**Comment by sharjeelsayed** [comment]
> The script from #41 seems to work.

Yes..#41 still works

**Comment by natterstefan** [comment]
I can also confirm that https://github.com/vitorgalvao/custom-alfred-iterm-scripts/issues/41 works with macOS 10.15.3 and iTerm 3.3.9.

**Comment by vitorgalvao** [comment]
There’s no need to keep reporting #41 works. I’m aware. [As mentioned](https://github.com/vitorgalvao/custom-alfred-iterm-scripts/issues/43#issuecomment-628289800), I’m waiting for Alfred 4.1 before deciding on a course of action.

**Comment by vitorgalvao** [comment]
I’ve just released a new version that may fix this. Please test and report back.

**Comment by alihazemfarouk** [comment]
> I’ve just released a new version that may fix this. Please test and report back.

Can confirm it's working with iTerm 3.3.11 and macOS 10.15.5. Thanks!

**Comment by vitorgalvao** [comment]
Thank you @alihazemfarouk.

Just published another version which changes some code around but should still work the same.

Closing and assuming it’s solved until further reports.
