### ISSUE TITLE
open action Terminal command in new tab

### ISSUE THREAD

**Issue by ahmeed83** [vitorgalvao/custom-alfred-iterm-scripts#47]
Hi, 

I have couple of scripts that I want to be run one after one. I made a workflow to do so but the problem is that happened n the same tab. How can I make alfred to open a new tab every time?

Example: 

1- cd /dir1/
1.1- npm install

2- cd /dir2/
2.1 mvn clean install

3 cd /dir3/
3.1 run kafka

**Comment by vitorgalvao** [comment]
> I made a workflow to do so

If you have a Workflow, share it. I can’t definitely say what’s wrong without seeing it.

Presumably you have everything in the same `Run Command`, so you need to have several, each with its own set of commands.

**Comment by ahmeed83** [comment]
That was exactly what I was looking for! Thank you very much for the amazing plugin. 

I was struggling for the whole day on making this is possible. But your plugin did it al. 

Thanks again!
