### ISSUE TITLE
Add start project rellease

### ISSUE THREAD

**Issue by limakzi** [vitorgalvao/custom-alfred-iterm-scripts#50]
Hi! 
Thank you for the script.
I would propose to make releases. I am using this project as a ghost, like probably, most of the Alfred users.
I love to track new releases and I noticed updates in this script only after reinstall (sic!).
How about making a standard release process and allow users to track releases?

**Comment by vitorgalvao** [comment]
[Done](https://github.com/vitorgalvao/custom-alfred-iterm-scripts/releases). But it’s unlikely you’ll ever see another release unless something breaks (because of Apple or iTerm2). The code has been pretty stable.
