### ISSUE TITLE
Feature/PR suggestion: add exit_on_run option

### ISSUE THREAD

**Issue by jackwellsxyz** [vitorgalvao/custom-alfred-iterm-scripts#55]
Hi Vitor, great script! I modified your code to add an `exit_on_run` property that will send "exit" to iTerm once it finishes running the query. Happy to send in a PR for this if you'd like.

**Comment by vitorgalvao** [comment]
If you’re exiting the terminal right after the command is run, you should be using a [Run Script Action](https://www.alfredapp.com/help/workflows/actions/run-script/) instead. If you’re using it for one-offs but need your aliases and other stuff from your shell, that’s what [RunCommand](https://github.com/vitorgalvao/alfred-workflows/tree/master/RunCommand) is for.

Thank you for the offer and the kind workds, but having the terminal always close after it runs the command doesn’t make sense in the context of Alfred’s feature.
