### ISSUE TITLE
Command Appears Before Shell Loads

### ISSUE THREAD

**Issue by renatohcampos** [vitorgalvao/custom-alfred-iterm-scripts#58]
It might just be me - but it seems like when a command is called, the text is pasted before the shell loads, and then is pasted again after the shell loads. Is anyone else getting this behavior?
![Screen Shot 2022-01-30 at 5 22 24 PM](https://user-images.githubusercontent.com/22178609/151727034-955d4d49-031a-4725-8b5f-11a465639177.png)

**Comment by vitorgalvao** [comment]
This is normal behaviour. Your shell’s startup is too slow so the text is written before it is ready. But it is only run once, when it’s ready, it is not being pasted twice. This behaviour is useful and controlled by iTerm.
