### ISSUE TITLE
Had to change apple script to get it to function

### ISSUE THREAD

**Issue by 23727** [vitorgalvao/custom-alfred-iterm-scripts#61]
For who it might help, 

Alfred 4.6.6 
iTerm 2 Build 3.5.0beta5

The script was not opening iTerm 2 for me. I changed all instances of "iTerm" to "iTerm 2" and it worked. 

Thank you

**Comment by vitorgalvao** [comment]
I’m testing the beta and that solution doesn’t work. But indeed something changed in the behaviour, so I’m looking into it. Thank you for letting me know.

**Comment by vitorgalvao** [comment]
I have just released the new version to address it, while keeping compatibility with the stable version.
