### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by michaelbasca** [vitorgalvao/custom-alfred-iterm-scripts#63]
Hi, this script doesn't do anything.  Is is still active?

**Comment by vitorgalvao** [comment]
The [latest release](https://github.com/vitorgalvao/custom-alfred-iterm-scripts/releases/tag/2022.1) was last month. Yes, it’s still active and has been pretty stable for over a year.

Please don’t just say “it doesn’t work” when reporting an issue, as that does not help with finding a cause. Describe your steps, what you expected, and what happened.

But first check System Preferences → Security & Privacy → Privacy → Automation. You likely have iTerm.app disabled under Alfred.

**Comment by michaelbasca** [comment]
When I used the custom option and place a command e.g. >ls, nothing happens.  When I place it back under Terminal option and I hit >ls my terminal window pops up and performs the command.  Iterm 2 is enabled in Automation.  Let me know if you need any other info.

**Comment by vitorgalvao** [comment]
What are your versions of macOS, Alfred, and iTerm?

> Iterm 2 is enabled in Automation.

Make sure you’re looking *under* Alfred; iTerm at the top level is not the same thing. Untick and retick the box, since sometimes macOS screws up the permissions, even if they show as enabled.

**Comment by michaelbasca** [comment]
Monterey 12.4
Alfred 5.0.1
iTerm2 3.4.16

Yes absolutely it's iTerm 2 under the Alfred directory, not top level. 
Unticked and reticked and nothing changed.
I reset Alfred based on FAQ:
https://www.alfredapp.com/help/troubleshooting/reset-alfred/
Then ran the script again and still nothing happened.  I made sure all permissions were enabled.

**Comment by vitorgalvao** [comment]
If you want to [share a video](https://support.apple.com/en-us/HT208721) of you enabling the feature in Alfred then running a command, maybe something will jump as a possible cause. Otherwise, and since you’re the only one experiencing this, you’ll have to figure out what’s atypical about your setup. Either way I’ll leave the issue open for a few days in case someone has an insight.

**Comment by mhorniq** [comment]
jumping in with the same issue.

Monterey 12.5, Alfred 5.0.1 [2067], iTerm 2 3.4.16

after pasting script in custom field nothing happens.

checked the settings you suggested, i don't have iTerm under automation there (see screenshot)

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/5346720/181925531-fd5c09cd-48b4-49f9-83c5-e1af54895567.png">

**Comment by michaelbasca** [comment]
Thanks a lot.  Here's the link to screen cast, confirming the permissions are correct, the script, the issue, and how it normally works with terminal.

[https://www.dropbox.com/s/d5o9p5oqikdxovs/Screen%20Recording%20at%2012.56.01%20PM.mov?dl=0](url)

**Comment by vitorgalvao** [comment]
Thank you @michaelbasca. Unfortunately, nothing jumped as wrong. Will still leave open for a few days.

@mhorniq In your case, you pasted the wrong thing. You’re supposed to run the command [in a terminal](https://support.apple.com/en-gb/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac) then paste. Or [manually copy the correct code](https://raw.githubusercontent.com/vitorgalvao/custom-alfred-iterm-scripts/master/custom_iterm_script.applescript).

**Comment by michaelbasca** [comment]
@vitorgalvao thanks and I just figured out the issue.  I reset Alfred and the issue still persisted.  So I decided to reinstall iTerm2 and that did the trick!  I imported my Alfred preferences and the issue did not crop back up :)

My issue is resolved, and again, thanks for getting back to me!
