### ISSUE TITLE
Script Running Before iTerm2 Initialized

### ISSUE THREAD

**Issue by Geoff12889** [vitorgalvao/custom-alfred-iterm-scripts#65]
Weird behavior when I change the following two property settings:

-- Set this property to false to reuse current tab
property open_in_new_tab : false

-- Set this property to true if iTerm is configured to launch without opening a new window
property iterm_opens_quietly : true

The script is input into iTerm before the session is initialized and the script does not get a chance to run. This behavior seems to work when the previous setting are reversed.

**Comment by Geoff12889** [comment]
I think I narrowed the issue down to this property setting:

-- Set this property to true if iTerm is configured to launch without opening a new window
property iterm_opens_quietly : true

My iTerm2 is set up to launch with a window, but when I run with this setting set to "false", a window does not, and I have to click the app icon in the dock to bring the window forward. I change this setting to "true" and a window does launch after passing in a script, but I run into the issue where the script does not run in the terminal (the argument gets passed, it just loads before the virtualization is initialized).

**Comment by Geoff12889** [comment]
I somewhat got it working. The only issue is I added a delay that would ideally only happen on the first instance if the application is closed. If the application is already opened and the virtualization already initiated, the delay should not be necessary.

Below is my code with my notes signed -GW

`-- For the latest version:
-- https://github.com/vitorgalvao/custom-alfred-iterm-scripts

-- Set this property to true to always open in a new window
property open_in_new_window : false

-- Set this property to false to reuse current tab
property open_in_new_tab : false

-- Set this property to true if iTerm is configured to launch without opening a new window
property iterm_opens_quietly : false

-- Handlers
on new_window()
  tell application "iTerm" to create window with default profile
end new_window

on new_tab()
  tell application "iTerm" to tell the first window to create tab with default profile
end new_tab

on call_forward()
  tell application "iTerm" to activate
end call_forward

on is_running()
  application "iTerm" is running
end is_running

on has_windows()
  if not is_running() then return false

  tell application "iTerm"
    if windows is {} then return false
    if tabs of current window is {} then return false
    if sessions of current tab of current window is {} then return false

    set session_text to contents of current session of current tab of current window
    if words of session_text is {} then return false
  end tell

  true
end has_windows

on send_text(custom_text)
  tell application "iTerm" to tell the first window to tell current session to write text custom_text
end send_text

-- Main
on alfred_script(query)
  if has_windows() then
    if open_in_new_window then
      new_window()
    else if open_in_new_tab then
      new_tab()
    else
      -- Reuse current tab
    end if
  else
    -- If iTerm is not running and we tell it to create a new window, we get two:
    -- one from opening the application, and the other from the command
    if is_running() or iterm_opens_quietly then
      new_window()
    else
      call_forward()
      -- Added new_window() since my iTerm2 was not opening a window when this script was intiated. Otherwise, when opening iTerm2 normally, a window is automatically opened. -GW
      new_window()
    end if
  end if

  -- Make sure a window exists before we continue, or the write may fail
  -- "with timeout" does not work with a "repeat"
  -- Delay of 0.01 seconds repeated 500 times means a timeout of 5 seconds
  repeat 500 times
    if has_windows() then
      -- Swapped call_forward() and send_text(query), unsure if there is a reason to have it reversed but it is working as-is -GW
      call_forward()
      -- Added half second delay. This allows the script time to push while the virtualization intiates the first time. It would be ideal on subsecquent scripts that the delay is removed and only used on the first instance. -GW
      delay 0.5
      send_text(query)
      exit repeat
    end if

    delay 0.01
  end repeat
end alfred_script`

**Comment by vitorgalvao** [comment]
I’m having trouble following your report. It’s not clear what values you’re using for the options, what your goal is, or what’s happening.

**Comment by vitorgalvao** [comment]
Glad you got it working, but since this isn’t widespread I don’t want to add an indiscriminate delay and make it slower for everyone. If you fix the reason why it’s slower on your machine (i.e. making it reproducible), I’ll look into making it work in that situation.
