### ISSUE TITLE
Running command results in no action

### ISSUE THREAD

**Issue by konradsemsch** [vitorgalvao/custom-alfred-iterm-scripts#66]
I'm running on macos ventura 13.2.1 (22D68) and just tried using the script but it results in no action taking place. Any ideas why that could be?

**Comment by vitorgalvao** [comment]
You don’t run the script, you add it in the preferences.

Please describe your full and exact steps. There is not enough information in the current report to understand what you’re doing incorrectly.

**Comment by rayei-wahan** [comment]
Perhaps similar to the OP, I recently followed the instructions on the main page, copied the script into Alfred's Terminal preferences, Application: Custom.
![Screenshot 2023-03-30 at 3 57 58 PM](https://user-images.githubusercontent.com/61288125/228962900-47cb1df0-e432-47b4-9a98-bf89b651413b.png).

I then summoned Alfred, typed ">pwd", and nothing happened. iTerm did not open a new window, nor did it open a new tab in an existing window nor run the command in an existing instance.

Changing Alfred's Terminal preferences to Terminal, then summoning Alfred and typing ">pwd" opened a Terminal window and printed my working directory as expected.

Specs: macOS Ventura 13.3 (22E252), Apple M2 Pro chip. Alfred 5.0.6 [2110].

**Comment by vitorgalvao** [comment]
@rayei-wahan What’s your iTerm2 version?

**Comment by rayei-wahan** [comment]
> Perhaps similar to the OP, I recently followed the instructions on the main page, copied the script into Alfred's Terminal preferences, Application: Custom. ![Screenshot 2023-03-30 at 3 57 58 PM](https://user-images.githubusercontent.com/61288125/228962900-47cb1df0-e432-47b4-9a98-bf89b651413b.png).
> 
> I then summoned Alfred, typed ">pwd", and nothing happened. iTerm did not open a new window, nor did it open a new tab in an existing window nor run the command in an existing instance.
> 
> Changing Alfred's Terminal preferences to Terminal, then summoning Alfred and typing ">pwd" opened a Terminal window and printed my working directory as expected.
> 
> Specs: macOS Ventura 13.3 (22E252), Apple M2 Pro chip. Alfred 5.0.6 [2110].

Nevermind, I restarted Alfred and I term opens as expected. Maybe I read the instructions to quickly and missed the need to restart. Sorry to waste your time. I'll wipe the egg from my face now. :)
