### ISSUE TITLE
Fix issue when sending long command

### ISSUE THREAD

**Issue by xtremforce** [vitorgalvao/custom-alfred-iterm-scripts#67]
I tried to send some particularly long commands with Alfred, but iTerms always cut my command in half, making it impossible to execute properly. Later, I discovered the reason was that the call_forwrad() was being called before send_text() had completed, causing the issue. Reversing the order of these two resolved the problem. And, adding a delay between them can make it more reliable.

```
if has_windows() then
      call_forward()
      delay 0.5
      send_text(query)
      exit repeat
    end if
```

**Comment by vitorgalvao** [comment]
> I tried to send some particularly long commands

How long is your command? I need an example to properly test. And what is your configuration (the `property` values at the top)? Copy and paste the whole script you have in Alfred’s Preferences as it’ll make it easier to diff.

I just retested with delays and `send_text()` must finish before `call_forward()` triggers, so your hypothesis only seems possible with a bug in iTerm2.

> And, adding a delay between them can make it more reliable.

In what way, specifically, is it unreliable without the delay? Adding delays to GUI automation operations is to be avoided at all costs, because even if a `0.5` delay works for you on your current machine, it may not work for someone else under a high load, for example. And from the observations above that shouldn’t make any difference.

I’m certainly willing to update the code, but seeing as this is the first instance of that problem I’ve seen for a script that has been working reliably for thousands of users for years, a proper understanding of what’s happening is necessary. I need to know what you’re seeing isn’t an oddity caused by your setup.

**Comment by xtremforce** [comment]
I use Alfred to call a shell script for batch processing multiple images, with the file paths as parameters for the script. If there are many files, the command can become very long. Previously, executing such lengthy code would get truncated.
It works after I changed the code.

Here's the example:
`sh ~/Path/to/batch_images_process.sh "/Users/System/Desktop/Focus/FocuSeeImages/img_1_2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/[pt] FocuSee_600x300@2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/[pt] FocuSee_786x180@2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/[pt] FocuSee_800x800@2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/[pt] FocuSee_820x200@2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/[pt] FocuSee_900x360@2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/[pt] FocuSee_1800x600@2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/[pt] TTime_500x900@2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/[pt]FocuSee_600x400@2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_1.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_2-resized.gif" "/Users/System/Desktop/Focus/FocuSeeImages/img_2.gif" "/Users/System/Desktop/Focus/FocuSeeImages/img_3_2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_3.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_4.gif" "/Users/System/Desktop/Focus/FocuSeeImages/img_5_2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_5.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_6_2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_6.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_7_2x.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_7.png" "/Users/System/Desktop/Focus/FocuSeeImages/img_8.gif"`

**Comment by vitorgalvao** [comment]
After some tests, I noticed that the command was truncated at 1024 character. That’s looked too neat of a “round” number (in computer terms) to be a coincidence so I investigated a bit more and [indeed there is a reason for the limitation](https://gitlab.com/gnachman/iterm2/-/issues/5711#note_28328722).

This code should get you sorted. It has a noticeable delay on long commands, but at least there’s no truncation. And by not hardcoding a delay, it should continue to work even if your shell becomes slower.

```AppleScript
-- For the latest version:
-- https://github.com/vitorgalvao/custom-alfred-iterm-scripts

-- Set this property to true to always open in a new window
property open_in_new_window : false

-- Set this property to false to reuse current tab
property open_in_new_tab : true

-- Set this property to true if iTerm is configured to launch without opening a new window
property iterm_opens_quietly : false

-- Handlers
on new_window()
  tell application "iTerm" to create window with default profile
end new_window

on new_tab()
  tell application "iTerm" to tell the first window to create tab with default profile
end new_tab

on call_forward()
  tell application "iTerm" to activate
end call_forward

on is_running()
  application "iTerm" is running
end is_running

on is_processing()
  tell application "iTerm" to tell the first window to tell current session to return is processing
end is_processing

on has_windows()
  if not is_running() then return false

  tell application "iTerm"
    if windows is {} then return false
    if tabs of current window is {} then return false
    if sessions of current tab of current window is {} then return false

    set session_text to contents of current session of current tab of current window
    if words of session_text is {} then return false
  end tell

  true
end has_windows

on send_text(custom_text)
  tell application "iTerm" to tell the first window to tell current session to write text custom_text
end send_text

-- Main
on alfred_script(query)
  if has_windows() then
    if open_in_new_window then
      new_window()
    else if open_in_new_tab then
      new_tab()
    else
      -- Reuse current tab
    end if
  else
    -- If iTerm is not running and we tell it to create a new window, we get two:
    -- one from opening the application, and the other from the command
    if is_running() or iterm_opens_quietly then
      new_window()
    else
      call_forward()
    end if
  end if

  -- macOS buffers TTY input to 1024 bytes, so if input is larger wait for session to be ready
  -- "with timeout" does not work with "repeat", so use a delay (0.01 * 500 means a timeout of 5 seconds)
  if length of query > 1024
    repeat 500 times
      if not is_processing() then exit repeat
      delay 0.01
    end repeat
  end if

  -- Make sure a window exists before we continue, or the write may fail
  -- "with timeout" does not work with "repeat", so use a delay (0.01 * 500 means a timeout of 5 seconds)
  repeat 500 times
    if has_windows() then
      send_text(query)
      call_forward()
      exit repeat
    end if

    delay 0.01
  end repeat
end alfred_script
```
